### ISSUE TITLE
Owner key must not be mandatory

### ISSUE THREAD

**Issue by sschiessl-bcp** [clockworkgr/bitshares-companion#1]
When creating an account the owner key must be entered, otherwise an exception is thrown after entering wallet password.

Furthermore, the default question should be to collect active and memo. The field to enter owner key could appear when a small button "Include owner key" or similar is clicked.

**Comment by clockworkgr** [comment]
Ok...will sort it out

**Comment by clockworkgr** [comment]
Fixed in https://github.com/clockworkgr/bitshares-companion/commit/2af365518eb3ac8892c16fa48dff79c5863c4ab5
