### ISSUE TITLE
Companion asks to allow receive identity without being asked for it

### ISSUE THREAD

**Issue by sschiessl-bcp** [clockworkgr/bitshares-companion#3]
```
this.holder.btscompanion.connect('BitShares Voting Widget').then(connected => {
                if(connected){
                    //this.btscompanion = btscompanion; Unbind from window and bind to your own state var to avoid extension hijacking
                    //window.btscompanion = null;
                    window.btscompanion.requestSignature({op_type: "transfer",op_data: {
                        "amount": {
                            "amount": 100000,
                            "asset_id": "1.3.0"
                        },
                        "extensions": [],
                        "fee": {
                            "amount": 10420,
                            "asset_id": "1.3.0"
                        },
                        "from": "1.2.386825",
                        "to": "1.2.386826"
                    }});

                }
            })
```

Executing the above will also trigger to access account ID
![image](https://user-images.githubusercontent.com/33128181/44073507-82b1413a-9f94-11e8-8258-a3df2bdf57dd.png)

This popup should only appear when accountId is requested

**Comment by clockworkgr** [comment]
the connect() essentially does a getAccount...

if you havent got the user's accountID, whats the point of asking him to sign a TX ? you dont even know what the TX is supposed to look like without his ID

**Comment by sschiessl-bcp** [comment]
If I vote for a worker and use the voteFor(workerId) command, the voting widget does not need to know anything about the account that wants to do the voting

**Comment by sschiessl-bcp** [comment]
New example:

Transfer looks like 
```
{op_type: "transfer",op_data: {
                        "amount": {
                            "amount": 100000,
                            "asset_id": "1.3.0"
                        },
                        "extensions": [],
                        "fee": {
                            "amount": 10420,
                            "asset_id": "1.3.0"
                        },
                        "from": "1.2.386825",
                        "to": "1.2.386826"
                    }}
```
Would be easy now to have `"from": "REPLACE"` with some keyword, and the companion inserts users account id before signing.

**Comment by clockworkgr** [comment]
I thought you were a proponent of keeping it as close to as interacting with bitsharesjs as possible?

I know the voting widget doesnt need it...But 90% of the use cases will also need account Id access to load up data first...

**Comment by sschiessl-bcp** [comment]
> I thought you were a proponent of keeping it as close to as interacting with bitsharesjs as possible?

I am, but if you do a `voteFor` call that opens up that use case immediately.

**Comment by clockworkgr** [comment]
It's also for bitshares-companion-js ...not here ..hehehehe

**Comment by sschiessl-bcp** [comment]
> It's also for bitshares-companion-js ...not here ..hehehehe

Oh damn ...
